server:
  port: 8086

app:
  security:
    internal-secret: lX4.G9-SecretKey-0ag6o
    gateway-filter:
      enabled: false

spring:
  application:
    name: order-service

  autoconfigure:
    exclude:
      - net.devh.boot.grpc.client.autoconfigure.GrpcDiscoveryClientAutoConfiguration

  datasource:
    url: jdbc:postgresql://localhost:5433/EC-order
    username: admin
    password: admin123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
    contexts: ${SPRING_LIQUIBASE_CONTEXTS:default,seed}

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

temporal:
  target: localhost:7233
  task-queue: ORDER_TASK_QUEUE

grpc:
  client:
    catalog-grpc-server:
      address: 'static://localhost:9090'
      negotiation-type: plaintext