changeLogFile=src/main/resources/db/changelog/db.changelog-master.xml
url=jdbc:postgresql://localhost:5432/EC-order
username=admin
password=admin123
driver=org.postgresql.Driver
classpath=src/main/resources
